# Generated by Django 3.2.3 on 2023-09-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='asignatura',
            field=models.ManyToManyField(blank=True, related_name='alumnos', to='course_management.Asignatura'),
        ),
    ]
